---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gateway-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.gateway: glob:*
spec:
  releaseName: gateway-dev
  forceUpgrade: true
  chart:
    git: git@github.com:ektakhandelwal/puma-gitops
    path: charts/gateway
    ref: master
  valuesFrom:
  - secretKeyRef:
      name: image-creds
      key: image-creds.yaml
  - secretKeyRef:
      name: gateway-license
      key: license.yaml
  values:
    replicaCount: 1
    container:
      image: docker.sandbox5.apimgcp.com/repository/docker-hosted/gateway
      tag: '4'
    imageCredentials:
      name: "docker.sandbox5.apimgcp.com"
      registry: "docker.sandbox5.apimgcp.com"
      username: "admin"
    hazelcast:
      enabled: false
    influxdb:
      host: "apim-service-metrics-runtime-influxdb.default"
    service:
      ports:
      - name: http
        internal: 8080
        external: 80
      - name: https
        internal: 8443
        external: 443
    gateway:
      license:
        accept: "true"
      env:
        ENV.PROPERTY.gateway.template: "New Testing environment"
        ENV.CONTEXT_VARIABLE_PROPERTY.env-configuration.example: "This is New Testing\
          \ environment"
        ENV.PASSWORD.password: "less secret test password"
        ENV.LISTEN_PORT.custom-https: '{ "protocol" : "HTTP", "port" : 12345, "enabledFeatures"
          : [ "Published service message input" ], "properties" : { "threadPoolSize"
          : "20" } }'





